// Interface automatically generated by schemas-to-ts

export enum Social {
  YOUTUBE = 'YOUTUBE',
  TWITTER = 'TWITTER',
  DISCORD = 'DISCORD',
  WEBSITE = 'WEBSITE',}

export interface SocialLink {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}
export interface SocialLink_Plain {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}

export interface SocialLink_NoRelations {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}

