// Interface automatically generated by schemas-to-ts

import { FeatureRow } from './FeatureRow';
import { FeatureRow_Plain } from './FeatureRow';
import { FeatureRow_NoRelations } from './FeatureRow';

export interface FeatureRowsGroup {
  features: FeatureRow[];
}
export interface FeatureRowsGroup_Plain {
  features: FeatureRow_Plain[];
}

export interface FeatureRowsGroup_NoRelations {
  features: FeatureRow_NoRelations[];
}

