// Interface automatically generated by schemas-to-ts

import { FeatureColumn } from './FeatureColumn';
import { FeatureColumn_Plain } from './FeatureColumn';
import { FeatureColumn_NoRelations } from './FeatureColumn';

export interface FeatureColumnsGroup {
  features: FeatureColumn[];
}
export interface FeatureColumnsGroup_Plain {
  features: FeatureColumn_Plain[];
}

export interface FeatureColumnsGroup_NoRelations {
  features: FeatureColumn_NoRelations[];
}

