// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Link_Plain } from './Link';
import { Link_NoRelations } from './Link';

export interface FooterSection {
  title?: string;
  links: Link[];
}
export interface FooterSection_Plain {
  title?: string;
  links: Link_Plain[];
}

export interface FooterSection_NoRelations {
  title?: string;
  links: Link_NoRelations[];
}

