// Interface automatically generated by schemas-to-ts

import { Media } from './Media';
import { ButtonLink } from './ButtonLink';
import { ButtonLink_Plain } from './ButtonLink';
import { ButtonLink_NoRelations } from './ButtonLink';

export interface Hero {
  title: string;
  description: string;
  picture: { data: Media };
  buttons: ButtonLink[];
}
export interface Hero_Plain {
  title: string;
  description: string;
  picture: Media;
  buttons: ButtonLink_Plain[];
}

export interface Hero_NoRelations {
  title: string;
  description: string;
  picture: number;
  buttons: ButtonLink_NoRelations[];
}

